---
# Source: gdpr-www/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gdpr-www
  labels:
    app: gdpr-www
    chart: gdpr-www-0.1.0
    release: gdpr-www
    heritage: Tiller
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: gdpr-www
    release: gdpr-www
---
# Source: gdpr-www/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gdpr-www
  labels:
    app: gdpr-www
    chart: gdpr-www-0.1.0
    release: gdpr-www
    heritage: Tiller
  annotations:
    flux.weave.works/tag.gdpr-www: glob:development-*
    flux.weave.works/automated: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gdpr-www
      release: gdpr-www
  template:
    metadata:
      labels:
        app: gdpr-www
        release: gdpr-www
    spec:
      imagePullSecrets:
      - name: 'docker-cfg'
      containers:
      - name: gdpr-www
        image: "intraedge/gdpr-www:development"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /en
            port: http
        readinessProbe:
          httpGet:
            path: /en
            port: http
        resources: {}
